app: spotme-auth-svc
sonar: true
project: spotme

docker:
  credsId: spotme-rest-jwt-jenkins

artifacts:
  - 'target/*.jar'
  - 'imageRef.properties'
  - 'pipeline.properties'
spinnaker_app: spotme-auth-svc

environments:
  - name: feature/
    deploy: true
    spinnaker:
      pipeline: "deploy-dev"
      parameters:
        # key: "value"
        
  - name: develop
    deploy: true
    spinnaker:
      pipeline: "deploy-dev"
      parameters:
        # key: "value"        

  - name: master
    deploy: true
    spinnaker:
      pipeline: "deploy-prod"
      parameters:
      # key: "value"
